var quito = [{
   "cod":"200",
   "message":0,
   "cnt":40,
   "list":[
      {
         "dt":1578787200,
         "main":{
            "temp":58.23,
            "feels_like":57.58,
            "temp_min":57.25,
            "temp_max":58.23,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":90,
            "temp_kf":0.54
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":80
         },
         "wind":{
            "speed":4.09,
            "deg":319
         },
         "rain":{
            "3h":0.75
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-12 00:00:00"
      },
      {
         "dt":1578798000,
         "main":{
            "temp":57.65,
            "feels_like":57.81,
            "temp_min":56.91,
            "temp_max":57.65,
            "pressure":1015,
            "sea_level":1015,
            "grnd_level":752,
            "humidity":85,
            "temp_kf":0.41
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":64
         },
         "wind":{
            "speed":1.48,
            "deg":64
         },
         "rain":{
            "3h":0.44
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-12 03:00:00"
      },
      {
         "dt":1578808800,
         "main":{
            "temp":55.8,
            "feels_like":55.31,
            "temp_min":55.31,
            "temp_max":55.8,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":751,
            "humidity":84,
            "temp_kf":0.27
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":51
         },
         "wind":{
            "speed":1.52,
            "deg":341
         },
         "rain":{
            "3h":0.06
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-12 06:00:00"
      },
      {
         "dt":1578819600,
         "main":{
            "temp":53.71,
            "feels_like":52.93,
            "temp_min":53.46,
            "temp_max":53.71,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":81,
            "temp_kf":0.14
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03n"
            }
         ],
         "clouds":{
            "all":28
         },
         "wind":{
            "speed":0.6,
            "deg":56
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-12 09:00:00"
      },
      {
         "dt":1578830400,
         "main":{
            "temp":55.08,
            "feels_like":53.37,
            "temp_min":55.08,
            "temp_max":55.08,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":74,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":19
         },
         "wind":{
            "speed":1.79,
            "deg":94
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-12 12:00:00"
      },
      {
         "dt":1578841200,
         "main":{
            "temp":67.42,
            "feels_like":65.32,
            "temp_min":67.42,
            "temp_max":67.42,
            "pressure":1015,
            "sea_level":1015,
            "grnd_level":752,
            "humidity":48,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.53,
            "deg":14
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-12 15:00:00"
      },
      {
         "dt":1578852000,
         "main":{
            "temp":67.87,
            "feels_like":64.76,
            "temp_min":67.87,
            "temp_max":67.87,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":749,
            "humidity":59,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":25
         },
         "wind":{
            "speed":7.2,
            "deg":340
         },
         "rain":{
            "3h":0.25
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-12 18:00:00"
      },
      {
         "dt":1578862800,
         "main":{
            "temp":61.68,
            "feels_like":59.85,
            "temp_min":61.68,
            "temp_max":61.68,
            "pressure":1009,
            "sea_level":1009,
            "grnd_level":749,
            "humidity":79,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":88
         },
         "wind":{
            "speed":6.08,
            "deg":312
         },
         "rain":{
            "3h":0.5
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-12 21:00:00"
      },
      {
         "dt":1578873600,
         "main":{
            "temp":57.02,
            "feels_like":55.8,
            "temp_min":57.02,
            "temp_max":57.02,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":749,
            "humidity":92,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":62
         },
         "wind":{
            "speed":4.76,
            "deg":326
         },
         "rain":{
            "3h":0.75
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-13 00:00:00"
      },
      {
         "dt":1578884400,
         "main":{
            "temp":56.8,
            "feels_like":56.55,
            "temp_min":56.8,
            "temp_max":56.8,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":87,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":48
         },
         "wind":{
            "speed":2.08,
            "deg":69
         },
         "rain":{
            "3h":0.44
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-13 03:00:00"
      },
      {
         "dt":1578895200,
         "main":{
            "temp":54.93,
            "feels_like":53.96,
            "temp_min":54.93,
            "temp_max":54.93,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":77,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":44
         },
         "wind":{
            "speed":0.87,
            "deg":163
         },
         "rain":{
            "3h":0.12
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-13 06:00:00"
      },
      {
         "dt":1578906000,
         "main":{
            "temp":53.06,
            "feels_like":51.96,
            "temp_min":53.06,
            "temp_max":53.06,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":80,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02n"
            }
         ],
         "clouds":{
            "all":23
         },
         "wind":{
            "speed":0.74,
            "deg":103
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-13 09:00:00"
      },
      {
         "dt":1578916800,
         "main":{
            "temp":54.77,
            "feels_like":53.98,
            "temp_min":54.77,
            "temp_max":54.77,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":54
         },
         "wind":{
            "speed":0.65,
            "deg":338
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-13 12:00:00"
      },
      {
         "dt":1578927600,
         "main":{
            "temp":64.78,
            "feels_like":63.05,
            "temp_min":64.78,
            "temp_max":64.78,
            "pressure":1015,
            "sea_level":1015,
            "grnd_level":752,
            "humidity":57,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ],
         "clouds":{
            "all":28
         },
         "wind":{
            "speed":2.84,
            "deg":352
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-13 15:00:00"
      },
      {
         "dt":1578938400,
         "main":{
            "temp":66.56,
            "feels_like":63.05,
            "temp_min":66.56,
            "temp_max":66.56,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":750,
            "humidity":62,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":40
         },
         "wind":{
            "speed":7.96,
            "deg":323
         },
         "rain":{
            "3h":0.25
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-13 18:00:00"
      },
      {
         "dt":1578949200,
         "main":{
            "temp":62.46,
            "feels_like":59.94,
            "temp_min":62.46,
            "temp_max":62.46,
            "pressure":1009,
            "sea_level":1009,
            "grnd_level":749,
            "humidity":75,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":6.91,
            "deg":302
         },
         "rain":{
            "3h":0.69
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-13 21:00:00"
      },
      {
         "dt":1578960000,
         "main":{
            "temp":57.16,
            "feels_like":55.83,
            "temp_min":57.16,
            "temp_max":57.16,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":750,
            "humidity":92,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":70
         },
         "wind":{
            "speed":5.06,
            "deg":323
         },
         "rain":{
            "3h":0.75
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-14 00:00:00"
      },
      {
         "dt":1578970800,
         "main":{
            "temp":56.55,
            "feels_like":56.77,
            "temp_min":56.55,
            "temp_max":56.55,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":89,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":71
         },
         "wind":{
            "speed":1.48,
            "deg":336
         },
         "rain":{
            "3h":0.25
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-14 03:00:00"
      },
      {
         "dt":1578981600,
         "main":{
            "temp":55.65,
            "feels_like":55.65,
            "temp_min":55.65,
            "temp_max":55.65,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":751,
            "humidity":87,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":75
         },
         "wind":{
            "speed":1.07,
            "deg":53
         },
         "rain":{
            "3h":0.13
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-14 06:00:00"
      },
      {
         "dt":1578992400,
         "main":{
            "temp":53.47,
            "feels_like":51.3,
            "temp_min":53.47,
            "temp_max":53.47,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":77,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":54
         },
         "wind":{
            "speed":2.42,
            "deg":125
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-14 09:00:00"
      },
      {
         "dt":1579003200,
         "main":{
            "temp":54.61,
            "feels_like":52.48,
            "temp_min":54.61,
            "temp_max":54.61,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":69
         },
         "wind":{
            "speed":1.88,
            "deg":129
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-14 12:00:00"
      },
      {
         "dt":1579014000,
         "main":{
            "temp":65.26,
            "feels_like":62.73,
            "temp_min":65.26,
            "temp_max":65.26,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":752,
            "humidity":52,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ],
         "clouds":{
            "all":45
         },
         "wind":{
            "speed":3.36,
            "deg":329
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-14 15:00:00"
      },
      {
         "dt":1579024800,
         "main":{
            "temp":66.33,
            "feels_like":62.74,
            "temp_min":66.33,
            "temp_max":66.33,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":750,
            "humidity":64,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":30
         },
         "wind":{
            "speed":8.43,
            "deg":317
         },
         "rain":{
            "3h":0.38
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-14 18:00:00"
      },
      {
         "dt":1579035600,
         "main":{
            "temp":61.74,
            "feels_like":58.69,
            "temp_min":61.74,
            "temp_max":61.74,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":749,
            "humidity":77,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":70
         },
         "wind":{
            "speed":7.85,
            "deg":313
         },
         "rain":{
            "3h":1.06
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-14 21:00:00"
      },
      {
         "dt":1579046400,
         "main":{
            "temp":56.68,
            "feels_like":55.18,
            "temp_min":56.68,
            "temp_max":56.68,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":750,
            "humidity":90,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":82
         },
         "wind":{
            "speed":4.74,
            "deg":316
         },
         "rain":{
            "3h":0.88
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-15 00:00:00"
      },
      {
         "dt":1579057200,
         "main":{
            "temp":56.12,
            "feels_like":55.45,
            "temp_min":56.12,
            "temp_max":56.12,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":90,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":97
         },
         "wind":{
            "speed":2.95,
            "deg":327
         },
         "rain":{
            "3h":0.38
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-15 03:00:00"
      },
      {
         "dt":1579068000,
         "main":{
            "temp":55.51,
            "feels_like":54.86,
            "temp_min":55.51,
            "temp_max":55.51,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":88,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":77
         },
         "wind":{
            "speed":2.28,
            "deg":43
         },
         "rain":{
            "3h":0.19
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-15 06:00:00"
      },
      {
         "dt":1579078800,
         "main":{
            "temp":53.49,
            "feels_like":52.29,
            "temp_min":53.49,
            "temp_max":53.49,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02n"
            }
         ],
         "clouds":{
            "all":17
         },
         "wind":{
            "speed":1.28,
            "deg":115
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-15 09:00:00"
      },
      {
         "dt":1579089600,
         "main":{
            "temp":54.68,
            "feels_like":52.09,
            "temp_min":54.68,
            "temp_max":54.68,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":72,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":20
         },
         "wind":{
            "speed":2.86,
            "deg":121
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-15 12:00:00"
      },
      {
         "dt":1579100400,
         "main":{
            "temp":66.76,
            "feels_like":64.78,
            "temp_min":66.76,
            "temp_max":66.76,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":48,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.06,
            "deg":360
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-15 15:00:00"
      },
      {
         "dt":1579111200,
         "main":{
            "temp":68.31,
            "feels_like":64.54,
            "temp_min":68.31,
            "temp_max":68.31,
            "pressure":1010,
            "sea_level":1010,
            "grnd_level":749,
            "humidity":58,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":1
         },
         "wind":{
            "speed":8.32,
            "deg":323
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-15 18:00:00"
      },
      {
         "dt":1579122000,
         "main":{
            "temp":63.46,
            "feels_like":60.33,
            "temp_min":63.46,
            "temp_max":63.46,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":748,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":46
         },
         "wind":{
            "speed":8.12,
            "deg":316
         },
         "rain":{
            "3h":0.81
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-15 21:00:00"
      },
      {
         "dt":1579132800,
         "main":{
            "temp":57.15,
            "feels_like":56.52,
            "temp_min":57.15,
            "temp_max":57.15,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":750,
            "humidity":89,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":60
         },
         "wind":{
            "speed":3.27,
            "deg":338
         },
         "rain":{
            "3h":0.63
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-16 00:00:00"
      },
      {
         "dt":1579143600,
         "main":{
            "temp":56.59,
            "feels_like":56.7,
            "temp_min":56.59,
            "temp_max":56.59,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":752,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":69
         },
         "wind":{
            "speed":1.03,
            "deg":42
         },
         "rain":{
            "3h":0.38
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-16 03:00:00"
      },
      {
         "dt":1579154400,
         "main":{
            "temp":55.15,
            "feels_like":54.55,
            "temp_min":55.15,
            "temp_max":55.15,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":751,
            "humidity":80,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":57
         },
         "wind":{
            "speed":0.78,
            "deg":64
         },
         "rain":{
            "3h":0.19
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-16 06:00:00"
      },
      {
         "dt":1579165200,
         "main":{
            "temp":53.65,
            "feels_like":52.65,
            "temp_min":53.65,
            "temp_max":53.65,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":749,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":10
         },
         "wind":{
            "speed":0.98,
            "deg":61
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-16 09:00:00"
      },
      {
         "dt":1579176000,
         "main":{
            "temp":55.44,
            "feels_like":52.75,
            "temp_min":55.44,
            "temp_max":55.44,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":751,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":18
         },
         "wind":{
            "speed":3.18,
            "deg":123
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-16 12:00:00"
      },
      {
         "dt":1579186800,
         "main":{
            "temp":68.41,
            "feels_like":66.45,
            "temp_min":68.41,
            "temp_max":68.41,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":46,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":22
         },
         "wind":{
            "speed":2.17,
            "deg":23
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-16 15:00:00"
      },
      {
         "dt":1579197600,
         "main":{
            "temp":69.33,
            "feels_like":66.7,
            "temp_min":69.33,
            "temp_max":69.33,
            "pressure":1010,
            "sea_level":1010,
            "grnd_level":749,
            "humidity":56,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ],
         "clouds":{
            "all":29
         },
         "wind":{
            "speed":6.29,
            "deg":341
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-16 18:00:00"
      },
      {
         "dt":1579208400,
         "main":{
            "temp":63.05,
            "feels_like":60.01,
            "temp_min":63.05,
            "temp_max":63.05,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":748,
            "humidity":77,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":49
         },
         "wind":{
            "speed":8.57,
            "deg":313
         },
         "rain":{
            "3h":0.31
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-16 21:00:00"
      }
   ],
   "city":{
      "id":3652462,
      "name":"Quito",
      "coord":{
         "lat":-0.2299,
         "lon":-78.5249
      },
      "country":"EC",
      "population":1399814,
      "timezone":-18000,
      "sunrise":1578741461,
      "sunset":1578785135
   }
}]; 